collision_detector:
  outside_polygon:
    - [ 0, 0 ]
    - [ 0, 10 ]
    - [ 10, 10 ]
    - [ 10, 0 ]

  inside_polygon:
    - [ [ 2.0, 9.0 ], [ 2.0, 6.0 ], [ 5.0, 6.0 ], [ 5.0, 9.0 ] ]
    - [ [ 2.0, 5.0 ], [ 2.0, 3.0 ], [ 3.5, 3.0 ], [ 3.5, 5.0 ] ]
    - [ [ 2.0, 0.0 ], [ 2.0, 2.0 ], [ 3.5, 2.0 ], [ 3.5, 0.0 ] ]
    - [ [ 7.0, 10.0 ], [ 7.0, 7.0 ], [ 10.0, 7.0 ], [ 10.0, 10.0 ] ]
    - [ [ 5.0, 5.0 ], [ 5.0, 4.0 ], [ 10.0, 4.0 ], [ 10.0, 5.0 ] ]
    - [ [ 8.0, 4.0 ], [ 8.0, 3.0 ], [ 10.0, 3.0 ], [ 10.0, 4.0 ] ]
    - [ [ 8.0, 0.0 ], [ 8.0, 1.5 ], [ 8.5, 1.5 ], [ 8.5, 0.0 ] ]
    - [ [ 5.0, 0.5 ], [ 5.0, 2.5 ], [ 6.5, 2.5 ], [ 6.5, 0.5 ] ]

  robot_shapes:
    - [ [ -0.3, -0.3 ], [ -0.3, 0.3 ], [ 0.3, 0.3 ], [ 0.3, -0.3 ] ]
    - [ [ -0.3, -0.3 ], [ -0.3, 0.3 ], [ 0.3, 0.3 ], [ 0.3, -0.3 ] ]

# start: [ [ 1.0, 9.0, -1.57 ] ]
start: [ [ 1.0, 9.0, -1.57 ], [ 9.0, 6.0, 3.14 ]]

# goal: [ [ 9.5, 1.0, -1.57 ] ]
goal: [ [ 9.5, 1.0, -1.57 ], [ 1.0, 1.0, -1.57 ]]

bounds:
  min_x: 0
  max_x: 10
  min_y: 0
  max_y: 10
type_: MultiRobotPathPlannerTask